### ISSUE TITLE
Overseerr Support

### ISSUE THREAD

**Issue by kiranshila** [kiranshila/Doplarr#5] opened 2021-08-12 15:56 UTC
Integrate Ombi/Overseer somehow

**Comment by VP-EN** [comment] 2021-08-16 19:25
Hey mate, not sure if this is in the scope of your Doplarr bot... But!

Overseerr has native support for separate 4K Radarr/Sonarr servers.. Overseerr also manages user permissions, like who can request 4K, who can't, who can request "normal" content, and who can't .. and so on.

It would be nice to have separate commands for the separate 4K Radarr/Sonarr servers, which are configured through Overseerr. So commands like `/4kmovie` and `/4ktv` to request through Overseerr, specifically using the separate 4K Radarr/Sonarr servers.

I made a similair request on the [requestrr repo](https://github.com/darkalfx/requestrr/issues/93).

**Comment by kiranshila** [comment] 2021-08-16 21:07
So, the tricky bit is that it's a slippery slope, once we add separate commands for individual profiles, we'd have to keep doing that for all potential profiles, which doesn't scale. The profile selection would happen inside the single `\request` interaction. I'm going to track that feature in #14.

So - we would need to connect the discord user to the overserr user and then add a separate interaction screen for profile selection that filters by what that user is able to request.

The reason we would do this inside the interaction is because it would be a hot mess to try to connect the overserr permissions to discord permission as the permissions structuring for the slash commands is a nightmare.

I haven't used either ombi or  overseerr, nor do I personally plan to, so I have to look more into how it all works.

There seem to be even more options than those two as well, I saw Conreq and Cheddarr just to name a few. The more APIs we add, the more difficult managing them all become, so I think I might just pick one for the time being.

From a cursory look, I think I will go with Overseerr. Of the people following this issue, are there any thoughts on this?

**Comment by onedr0p** [comment] 2021-08-16 21:14
Overseerr looks like the most popular choice of them all. The developers are super responsive and their app is very fast and very pretty. 

If anything you could deploy multiple `Doplarr` bots with different profiles configured to each one.

**Comment by cpt-kuesel** [comment] 2021-08-17 07:29
I vote for Overseerr Support as well. Their API structure is well built, at least thats what I gathered from talking with the requestrr and lunasea devs.

**Comment by kiranshila** [comment] 2021-08-17 16:17
Great! I'm going to work on the backlog of a few of these easier bugs/enhancements first, then I'll dive into this.

**Comment by onedr0p** [comment] 2021-08-17 16:25
@kiranshila thanks, looking forward to it!

**Comment by onedr0p** [comment] 2021-08-17 16:30
Also, here's a link to their API docs https://api-docs.overseerr.dev/

**Comment by kiranshila** [comment] 2021-08-18 05:35
I've been reading the overseer docs, seems straightforward. The fact that users can "just have" a discord id as part of their metadata makes this pretty easy. I'm going to need to do some checks to make sure that if we are using overseer, validate that the user can perform the request and if not, return a permission error dialog.

**Comment by cpt-kuesel** [comment] 2021-08-18 07:28
i am running overseerr and am willing to test anything you need tested in that regard!

**Comment by ahkamyaqeen** [comment] 2021-08-19 12:34
@kiranshila if you are open to pull requests, I'd love to help implement this feature (I do have a background in using Clojure)

**Comment by kiranshila** [comment] 2021-08-20 02:46
@ahkamyaqeen Yeah, if you'd like - I was going to tackle it this weekend, though.

**Comment by kiranshila** [comment] 2021-08-22 00:22
Started today - the api is actually a little wonky, not using the modern query params spec, which is throwing errors for search terms with spaces as the Java 11 URLEncoder encodes spaces as `+`.

I opened an issue here https://github.com/sct/overseerr/issues/2010

**Comment by onedr0p** [comment] 2021-08-22 01:29
@kiranshila there's a interesting stackoverflow about that issue. Seems pretty lengthy lol

https://stackoverflow.com/questions/4737841/urlencoder-not-able-to-translate-space-character

**Comment by kiranshila** [comment] 2021-08-22 01:31
Yeah, `+` is correct, Java isn't wrong lol, its a bug in Overseerr. I have a fix in place rn, it's just annoying haha

**Comment by onedr0p** [comment] 2021-08-22 01:35
Oh definitely a Bug on their end, I'm just mentioning you can likely workaround it for now until it's fixed by them upstream. The first answer in the stackoverflow seemed like it would do.

**Comment by kiranshila** [comment] 2021-08-22 01:36
The specific HTTP wrapper I am using does a URI encode before it submits the request anyway, so I am manually creating the query param string instead of the nice `{:query-params ...` construct. URI encoding puts spaces to `%20`, so it works out.

**Comment by kiranshila** [comment] 2021-08-24 00:31
Made a lot of progress today, requesting movies basically works:

You get an error message in discord for quota limits

![image](https://user-images.githubusercontent.com/6305359/130536563-f598ffdf-44ec-4331-ba27-d4a268792698.png)
 
And an error for missing associated account
![image](https://user-images.githubusercontent.com/6305359/130536677-1d902b38-a1bc-4e98-8347-9eab80c43577.png)

I think I prefer this - requiring you have a mapping from user in overseerr to discord rather than having a default, but let me know what you think.

**Comment by cpt-kuesel** [comment] 2021-08-24 07:42
I like your approach on this!
My Overseerr users that are on my Discord Server all have their respective Discord ID mapped. So I am well prepared 😄 

Which profile do you use when you send the request to Overseerr? Do you take the default one for movies/shows that is configured in Overseerr? Or does the user need to choose it when I have multiple? 
My preference would just be default profile.

**Comment by VP-EN** [comment] 2021-08-24 14:55
It would be nice if checked for permission(s) as well, and reported back to the user if they don't have permission. E.g. to the profiles associated with the 4K Sonarr / Radarr instances.

**Comment by kiranshila** [comment] 2021-08-24 17:40
> I like your approach on this!
> My Overseerr users that are on my Discord Server all have their respective Discord ID mapped. So I am well prepared smile
> 
> Which profile do you use when you send the request to Overseerr? Do you take the default one for movies/shows that is configured in Overseerr? Or does the user need to choose it when I have multiple?
> My preference would just be default profile.

As far as I can tell, I can't actually select the profile for the requests via the API, so it will always use whatever is setup in Overseerr

**Comment by kiranshila** [comment] 2021-08-24 17:42
> It would be nice if checked for permission(s) as well, and reported back to the user if they don't have permission. E.g. to the profiles associated with the 4K Sonarr / Radarr instances.

What permissions are you referring to? Just 4K vs non-4K, or quota limits, or other stuff. I'm still trying to think of a nice way to do the 4K split, but it looks like that requires having two different servers up, it can't just use a different profile afaik.

**Comment by VP-EN** [comment] 2021-08-24 18:32
> > It would be nice if checked for permission(s) as well, and reported back to the user if they don't have permission. E.g. to the profiles associated with the 4K Sonarr / Radarr instances.
> 
> What permissions are you referring to? Just 4K vs non-4K, or quota limits, or other stuff. I'm still trying to think of a nice way to do the 4K split, but it looks like that requires having two different servers up, it can't just use a different profile afaik.

Exactly what I'm referring to (the 4K vs the non-4K permissions).
To use 4K instances in Overseerr, you'll need separate Radarr / Sonarr instances for that. 
So, in Overseerr, it's usually setup (if you want to use 4K instances) like so:
1x Radarr for non-4K movie content
1x Sonarr for non-4K TV content
1x Radarr for 4K movie content
1x Sonarr for 4K TV content
All instances are separate at doesn't share profiles.

In my case, I've just named the non-4K Radarr/Sonarr profiles to "HD-1080p" and the 4K Radarr/Sonarr profiles to "UHD-4K". So they do have different profile names, not sure if that matters at all.

E.g.
https://i.imgur.com/79ymn1c.png

**Comment by kiranshila** [comment] 2021-08-24 18:53
Got it. Yeah, I'll need to chew on that a bit - I'll probably do it like the drop down for profile select, but I have to find which API endpoint lets me check if a user has permission for that.

**Comment by cpt-kuesel** [comment] 2021-08-24 23:19
just for clarification, i meant the overseer profiles as well, @VP-EN did a better job describing it :)

**Comment by VP-EN** [comment] 2021-08-30 17:36
Hey @kiranshila, I'm not sure how far you are with this, but I got to think :smile: 
Is it possible to add an (optional) option for Doplarr to request content on both profiles (regular + 4K)?

E.g.. If one user tries to request a Movie in 4K, that it also sends the same request (same movie) to the regular sonarr/radarr as well. 

Not sure if "options" are a part of Doplarr, so forgive me if this should be a in a separate GH issue.

**Comment by kiranshila** [comment] 2021-09-08 18:10
Sorry I've been quiet on this - got a ton of school stuff to catch up on. I'll finish this up soon.

**Comment by kiranshila** [comment] 2021-09-12 23:51
Ok I think I got it all working - if someone with an overseerr setup wants to try it out, check out the `ghcr.io/kiranshila/doplarr:overseerr` docker image

**Comment by kiranshila** [comment] 2021-09-12 23:54
If y'all don't find any major problems, I'm ready for the realease

**Comment by onedr0p** [comment] 2021-09-13 07:40
@kiranshila it would be good to know what environment variables to set :) But go ahead and merge it. I'm sure there will be feedback after you release it.

**Comment by kiranshila** [comment] 2021-09-13 07:42
Oh sorry, it's in the readme in this branch. You just set overseerr_url and overseerr_api, just like radarr and sonarr

**Comment by cpt-kuesel** [comment] 2021-09-13 09:20
I tried it and movies and tv shows work as expected.

Anime shows can't be requested, at least thats the conclusion i have come to.

Also requesting something thats already available gives the user no feedback and doesn't close the request.

**Comment by cpt-kuesel** [comment] 2021-09-13 09:21
To clarify on animes:
I am able to click request and get the response has been requested, but the actual request doesnt go through

**Comment by VP-EN** [comment] 2021-09-13 11:35
I'm quite busy today, so I'll only be able to test it tomorrow..

**Comment by kiranshila** [comment] 2021-09-13 15:42
@cpt-kuesel  
> Also requesting something thats already available gives the user no feedback and doesn't close the request.

Ah yes - forgot about that.

> I am able to click request and get the response has been requested, but the actual request doesnt go through

I am unable to reproduce this. Is there any error in the log? Is your anime setup somehow different?

**Comment by cpt-kuesel** [comment] 2021-09-13 15:50
I didn't see any errors in doplarr or overseerr logs unfortunately.

I don't think my anime setup is different. Both tv shows and anime are defined in the default profile for sonarr and differ only in root folder and tags.
![image](https://user-images.githubusercontent.com/79487102/133115783-0a7d79ba-4cab-451e-b3d4-47e319f84560.png)

**Comment by cpt-kuesel** [comment] 2021-09-13 16:20
Okay so I tried a bit more and was partially successful.
I did manage to request the anime shows i couldn't request before.

And I think I know the problem.
I can only request them if choose a specific season. If i choose all seasons the request doesnt go through.

**Comment by kiranshila** [comment] 2021-09-13 17:55
When you say it doesn't go through - like the request isn't showing up at all in Overseerr?

**Comment by cpt-kuesel** [comment] 2021-09-13 17:59
Correct, it never reaches Overseerr.
Not even in the overseerr logs.

**Comment by onedr0p** [comment] 2021-09-14 03:24
I was able to get this working and tested against adding a movie and tv show  🎉

**Comment by kiranshila** [comment] 2021-09-14 03:28
I think after I fix whatever is happening with @cpt-kuesel's anime and add a duplicate request message, we should be good to go

**Comment by VP-EN** [comment] 2021-09-17 19:11
I'm probably just an idiot, but I followed the guide quite closely, added the bot..
```
docker run \
-e OVERSEERR_URL='https://overseerr.xxxx.com' \
-e OVERSEERR_API='xxxxxxxxxxxxxxxxxxxxxxxxx=' \
-e BOT_TOKEN='xxxxxxxxxxxxxxxxxxxxxxxx' \
-e ROLE_ID='xxxxxxxxxxxxxxxxxxxxxxxx' \
--name doplarr ghcr.io/kiranshila/doplarr:overseerr
```

Getting this from the docker logs:
```
19:05:38,774 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback-test.xml]
19:05:38,774 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback.groovy]
19:05:38,774 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [logback.xml] at [jar:file:/app/target/Doplarr.jar!/logback.xml]
19:05:38,778 |-INFO in ch.qos.logback.core.joran.spi.ConfigurationWatchList@b0e5507 - URL [jar:file:/app/target/Doplarr.jar!/logback.xml] is not of type file
19:05:38,828 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - debug attribute not set
19:05:38,828 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
19:05:38,830 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [CONSOLE]
19:05:38,863 |-WARN in ch.qos.logback.core.ConsoleAppender[CONSOLE] - This appender no longer admits a layout as a sub-component, set an encoder instead.
19:05:38,863 |-WARN in ch.qos.logback.core.ConsoleAppender[CONSOLE] - To ensure compatibility, wrapping your layout in LayoutWrappingEncoder.
19:05:38,863 |-WARN in ch.qos.logback.core.ConsoleAppender[CONSOLE] - See also http://logback.qos.ch/codes.html#layoutInsteadOfEncoder for details
19:05:38,864 |-INFO in ch.qos.logback.classic.joran.action.RootLoggerAction - Setting level of ROOT logger to ERROR
19:05:38,864 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [CONSOLE] to Logger[ROOT]
19:05:38,864 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
19:05:38,864 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@6bbe50c9 - Registering current configuration as safe fallback point

```

Assuming this is alright, since the bot is showing it's online.

but I have a problem - the `/request` options are greyed out. I double checked the permissions given to the assigned role.. 
The "Use Application Commands" is set to enabled both in the role and in the channel I'm trying to use..

https://i.imgur.com/tposyGB.png

**Comment by kiranshila** [comment] 2021-09-17 19:19
@VP-EN Yeah, I should probably bold that or something - that seems to be the most common thing people are missing. This is an artifact of the discord slash command permissions nonsense, there isn't really a way around it.

**Comment by VP-EN** [comment] 2021-09-17 19:32
> @VP-EN Yeah, I should probably bold that or something - that seems to be the most common thing people are missing. This is an artifact of the discord slash command permissions nonsense, there isn't really a way around it.

Slightly annoying, but that's not your fault 😄  I guess I'll create some trash role for the sole purpose of the bot 👍 

The requesting works very good though. Again, as you already mentioned, it would be awesome with both a "this is already on Plex", if Overseerr knows it's already on Plex, or "this has already been requested" if Overseerr already knows it has been requested, and so on.

Thanks a lot for your work on this 👍

**Comment by kiranshila** [comment] 2021-09-17 19:36
> Slightly annoying, but that's not your fault smile I guess I'll create some trash role for the sole purpose of the bot +1

An alternative idea would be to make the role bit optional, if you want everyone on the server to have access to it, then we could just not use a role at all.  Those are the two options the discord API has, all or nothing.

**Comment by VP-EN** [comment] 2021-09-17 19:37
I think assigning it to a certain part of my Discord is sufficient in my case. 

I'm wondering how I can limit the bot to only work in a specific channel though. Do you have any thoughts on this?

**Comment by kiranshila** [comment] 2021-09-17 19:43
>I'm wondering how I can limit the bot to only work in a specific channel though. Do you have any thoughts on this/ideas?

It's not possible with the current slash command API, that's why we need the role.

**Comment by VP-EN** [comment] 2021-09-17 19:51
> 
> 
> > I'm wondering how I can limit the bot to only work in a specific channel though. Do you have any thoughts on this/ideas?
> 
> It's not possible with the current slash command API, that's why we need the role.

I see, thanks again mate. You're a legend.

**Comment by VP-EN** [comment] 2021-09-17 19:59
Sorry to spam up this issue.. but I have this one user on Discord I tried to test this with.
I copied and added his Discord ID to his profile on Overseerr, but when he's trying to request, he gets the `You do not have an associated account on Overseerr` message. 

It works on my own user, and I just copied my own ID into Overseerr.

**Comment by kiranshila** [comment] 2021-09-17 20:14
Ooo interesting - I suppose I should try to add more than one user to my test setup here haha

**Comment by VP-EN** [comment] 2021-09-17 20:15
**Edit:** The user in question 👍 
https://i.imgur.com/fRBQRvJ.png

**Comment by VP-EN** [comment] 2021-09-17 20:23
Ah shit mate, I think I figured it out 👍 

I took my friends ID and put it into the admin account of Overseerr - and then it worked. 

So I think there's something going on there 😄

**Comment by kiranshila** [comment] 2021-09-17 20:42
...uhhh haha. I'll take a look. Something is up with https://github.com/kiranshila/Doplarr/blob/5c68b56c35be43e597b6600211ea28c4202920a2/src/doplarr/overseerr.clj#L34-L46 then

**Comment by kiranshila** [comment] 2021-09-17 20:43
This seemed a little hacky anyway, but there wasn't an obvious way to connect the overseerr user account to the discord ID

**Comment by VP-EN** [comment] 2021-09-17 21:08
Clojure code looks strange to me lol. But to clarify, the bot only seems to allow the ID/user associated with the owner account of the O verseerr instance if that makes sense.

**Comment by kiranshila** [comment] 2021-09-18 00:00
@VP-EN I just tried a Local User and Plex User in overseerr and have not been able to reproduce the issue.

**Comment by VP-EN** [comment] 2021-09-18 08:02
In my case, both of the users are imported from Plex and not local Overseerr users. Not sure if that makes any difference.

**Comment by cpt-kuesel** [comment] 2021-09-18 10:57
I will try and follow your steps.
But I will probably only have time this evening. Will report back with my findings!

**Comment by VP-EN** [comment] 2021-09-18 11:22
I'm not sure you need to - the issue lies in this part of the code
https://github.com/kiranshila/Doplarr/blob/5c68b56c35be43e597b6600211ea28c4202920a2/src/doplarr/overseerr.clj#L28-L32

It uses the API call GET from `/user`, but by default that only gets the first 10 users.. So the issue will only appear if you have more than 10 users, and if the user in question will be the 11th (or later) user.
By forcing it to get more users, like `/user?take=1000`, it'll actually work as intended 👍 

But thanks anyways 👍

**Comment by kiranshila** [comment] 2021-09-18 18:05
Awesome detective work @VP-EN! Nowhere in the docs could I find that the users endpoint is paged as well. The docs clearly say get "all" users.

Great find. I'll get it fixed.

**Comment by VP-EN** [comment] 2021-09-18 18:37
> 
> 
> Awesome detective work @VP-EN! Nowhere in the docs could I find that the users endpoint is paged as well. The docs clearly say get "all" users.
> 
> Great find. I'll get it fixed.

Yeah, thanks. Found it by doing the `https://overseerr.urlremote.com/api/v1/user` and only saw 10 results. Then it clicked lol.

Anyways, I'm not sure if I asked this - is there any way for you to implement an option, where IF a user requests some movie/series in 4K, that's not already present in non-4K, it'll request both of them?
e.g. if a user requests "Die Hard" in 4K, and it's not already present on Plex, in either 4K or not, it'll send a request to both "profiles" (4K + Non-4K)?

**Comment by kiranshila** [comment] 2021-09-18 18:54
Yeah I'd say make a separate issue.

> @VP-EN https://overseerr.urlFromRemoteHost.com/api/v1/user/66 shows the correct discordId of the dpzTEST user

This is genius. Absolutely nowhere in the API docs does it say that the user endpoint returns the discord id. That makes everything so much simpler, I don't have to do this whole get all users thing. https://api-docs.overseerr.dev/#/users/get_user__userId_

It doesn't  even mention the settings block.

**Comment by kiranshila** [comment] 2021-09-18 18:57
Yeah all of that code is now
 ```clojure
(defn discord-id [ovsr-id]
  (a/go
    (->> (a/<! (GET (str "/user/" ovsr-id)))
         (then #(s/select-one [:body :settings :discordId] %))
         (else utils/fatal-error))))
```
So much better.

**Comment by kiranshila** [comment] 2021-09-18 19:22
Lol requestrr does exactly what you  proposed @VP-EN 

https://github.com/darkalfx/requestrr/blob/7c42356bcd1855e8d4fab2f18c3d0bd854f5a720/Requestrr.WebApi/RequestrrBot/DownloadClients/Overseerr/OverseerrClient.cs#L351

**Comment by kiranshila** [comment] 2021-09-18 19:50
Alright here is my solution, ping the endpoint once to find number of ids, then get all of them. That's the only way without having a magic maximum users number
```clojure
(defn num-users []
  (a/go
    (->> (a/<! (GET "/user" {:query-params {:take 1}}))
         (then #(s/select-one [:body :pageInfo :results] %))
         (else utils/fatal-error))))

(defn all-users []
  (a/go
    (->> (a/<! (GET "/user" {:query-params {:take (a/<! (num-users))}}))
         (then #(->> (s/select-one [:body :results] %)
                     (map :id)
                     (into [])))
         (else utils/fatal-error))))
```

**Comment by VP-EN** [comment] 2021-09-18 20:00
I think that's good 😄

**Comment by kiranshila** [comment] 2021-09-18 20:56
Alright, give the most recent docker image on this  branch a try - should have a message on the thing being requested, and fix the number of users error.

**Comment by VP-EN** [comment] 2021-09-18 21:54
I'll test in a short while 👍 I'll edit this post with the "results"

**Comment by kiranshila** [comment] 2021-09-18 22:20
Very helpful! Thank you!

Yeah the requested deal has a few more states  that I missed. I also noticed that things *currently downloading* also show up as un-requested.

**Comment by kiranshila** [comment] 2021-09-19 18:43
@VP-EN I found the bug that was causing the those issues, I forgot to pass in the bool that checks if the request was 4K. I also overhauled the response messages for the different media states. I'm finishing up these patches, I basically rewrote all the interaction flow control so now there is a single state machine that controls it, making the whole thing easier to modify instead of a ton of nested ifs.

**Comment by VP-EN** [comment] 2021-09-19 18:55
Sounds awesome 😁

**Comment by kiranshila** [comment] 2021-09-19 19:55
Ok whenever y'all get a chance, please give the latest build a try

**Comment by VP-EN** [comment] 2021-09-20 18:55
Finally had a few minutes to test it @kiranshila. 

Tried the latest build as of the time of this post:
**What works:**
- The error messages seem to work now!
- If a movie already exists on Plex, it'll report it correctly: `This is already available!`
- If a "regular" request is already registered in Overseerr, it'll correctly report: `This is currently processing and should be available soon.`
- If a "4K" request is already registered in Overseerr, it'll correctly report: `This is currently processing and should be available soon.`
- 

**Issues:**
- Requesting a movie (regular profile) that's NOT present in Plex, results in nothing happening.
- Requesting a movie (4K profile) that's NOT present in Plex, results in nothing happening. 
- Requesting 4K on a movie that's already present in 1080p on Plex, results in nothing happening. Nothing apparent to see in logs.
- Essentially can't request anything new, that's not present on Plex. When you click either "Request" or "Request 4K", nothing happens at all.

**Comment by kiranshila** [comment] 2021-09-21 18:01
@VP-EN Found the bugs, should be squashed now

**Comment by VP-EN** [comment] 2021-09-21 19:40
Seems to work perfectly now 😄 I can atleast request movies now quite seamlessly.

One issue though.. In Overseerr, there's a setting called `Allow Partial Series Requests`. 
This bot doesn't really "respect" that choice, since using `/request series {term}` will ask what season you want to request, and is able to circumvent this limitation set by the user in Overseerr settings.

It would be nice if the bot would check Overseerr if `Allow Partial Series Requests` is enabled or not:
https://i.imgur.com/7O2j0nf.png

If it's enabled, then it **should** be possible to request individual seasons, and if's it's disabled (not allowed) the only option should be `All Seasons` when requesting a series.

**Comment by kiranshila** [comment] 2021-09-21 20:00
Oh interesting - didn't even know that option existed. Should be easy enough to implement.

**Comment by kiranshila** [comment] 2021-09-21 20:01
I'm surprised Overseerr doesn't throw an error when requesting partial seasons

**Comment by VP-EN** [comment] 2021-09-21 20:04
> 
> 
> I'm surprised Overseerr doesn't throw an error when requesting partial seasons

Yeah kinda thought that would happen as well. Tested in, just in case lol 👍 

Also, not sure if this is relevant and/or avoidable, but the docker instance crashes when a user inputs a imdb url.. 
I'm guessing it crashes when other urls are put in.

**Comment by kiranshila** [comment] 2021-09-21 20:05
As like a query term?

**Comment by VP-EN** [comment] 2021-09-21 20:09
Yeah

**Comment by kiranshila** [comment] 2021-09-21 20:14
Buh? Was there an error?

**Comment by VP-EN** [comment] 2021-09-21 20:17
Nah, not even. I must've tried on a previous version, where it happened. Now when I put in a url, nothing seems to happen, other than a "no results" message

**Comment by VP-EN** [comment] 2021-09-21 21:09
also just tested your latest commit, it does seem to register that I've disabled the `Allow Partial Series Requests` and now only gives me the choice of All Seasons 👍 
I don't think I have anything more to add for now lol, other than my other [feature request](https://github.com/kiranshila/Doplarr/issues/22) 😉

**Comment by kiranshila** [comment] 2021-09-21 21:11
Yeah I just have it skip the season selection altogether if that is set.

I broke something in the direct sonarr backend though, I'm going to fix that, go through the tests again to make sure it's all still working, then publish.

**Comment by kiranshila** [comment] 2021-09-21 23:10
Alright @VP-EN I fixed that NPE

**Comment by VP-EN** [comment] 2021-09-22 08:55
Hey @kiranshila 

Tried the latest commit as of this post

Tried requesting series again, and it says it has been requested.
But looking in Overseerr, there's nothing there.

E.g.
- Requesting a series, `The Second Husband` (not present in either Sonarr or Plex)
- Requesting it in 1080p, and afterwards in 4K
- Nothing appears in Overseerr
- Tried requesting it again - it says `This has been requested!.
- Looking in Sonarr, the series is not present.

A bit different output from the logs this time:
https://0bin.net/paste/HbQjWEST#YvGXqe9O5a3Q9Ihch1KNh+dP0+k-ZitrN/j1nw7ZiCE

Tried removing the docker instance + image, and re-tried:
- It still says the series has been requested, but still not present in either Sonarr or Overseerr
- Can you reproduce this?? Seems a bit weird to me

**Comment by kiranshila** [comment] 2021-09-22 18:19
Yeah sorry, I was messing with the build and went to bed. There is a bug in the newer 1.11.0-alpha2 clojure - going back to alpha1 fixes parts of it. Also found a bug in the finding the status of a new series. Working it now.

**Comment by kiranshila** [comment] 2021-09-22 18:38
Alright @VP-EN I think I got that sorted. How many bugs could there possibly be haha

**Comment by kiranshila** [comment] 2021-09-22 19:43
I wouldn't say short - we've been at this a while haha!

**Comment by VP-EN** [comment] 2021-09-22 19:43
Haha yeah true 😆

**Comment by kiranshila** [comment] 2021-09-22 19:44
I'm going to do a few last tests with the direct api then publish the release!

**Closed** 2021-09-22 19:45 UTC
Labels: enhancement

**Comment by AstralDestiny** [comment] 2021-09-23 01:02
So not sure what I did wrong when trying it out but I don't see any slash commands not even greyed out stuff either. Bot is online but not seeing commands nor is it responding to any commands, I'm using it in container with docker.

**Comment by AstralDestiny** [comment] 2021-09-23 01:13
It has the Admin one that grants it all permissions so I only assume that's not an issue in the end 
![image](https://user-images.githubusercontent.com/20157872/134441607-ccf3b1b2-334e-4104-8765-e9b1f7f357bb.png)

**Comment by kiranshila** [comment] 2021-09-23 01:17
@AstralDestiny I wouldn't give the bot admin - as it mentions there, that is generally not a good idea.
What matters here is the OAuth2 permissions (how you invited the bot to your server). The important ones being `applications.commands` and `bot`

**Comment by kiranshila** [comment] 2021-09-23 01:18
So when you invite the bot to your server it will say something like

![image](https://user-images.githubusercontent.com/6305359/134441969-6dff1125-ff40-48e2-b107-583ce9ebe893.png)

**Comment by AstralDestiny** [comment] 2021-09-23 01:20
Yeah I missed the part about OAuth my bad. Ahaha

**Comment by AstralDestiny** [comment] 2021-09-23 01:22
I'm just laughing at myself I was blind.

**Comment by praneethbr** [comment] 2024-01-21 03:12
HI @kiranshila, not sure if this thread is still active but I thought I would check here because I cant seem to find any information on failed requests. When I request something on doplarr and radarr/sonarr cant find it, it doesn't get me a failed message in doplarr. Not sure if this is an issue with overseerr. Anyone else noticing this issue?
